#!/usr/bin/env bash
# Self-extracting deploy script for unified-coding-plan-balancer.
#
# This file is generated by `pnpm bundle`. It embeds a gzipped tarball of the
# Next.js standalone build at the end of the file, after the __PAYLOAD__ marker.
#
# Usage:
#   ./deploy <target-dir> <env-file>
#
# Behaviour (mirrors the manual recipe):
#   rm -rf <target-dir>
#   mkdir -p <target-dir>
#   tar xzf <embedded payload> -C <target-dir>
#   pm2 del ucpb 2>/dev/null || true
#   cp <env-file> <target-dir>/.env
#   cd <target-dir> && pm2 start --name ucpb 'node server.js'
#
set -euo pipefail

PROG=$(basename "$0")

usage() {
  cat <<USAGE
Usage: ./$PROG <target-dir> <env-file>

  target-dir   Directory to extract the build into. Will be wiped if it exists.
  env-file     Path to the .env file to copy into target-dir/.env

Example:
  ./$PROG /opt/ucpb /etc/ucpb/.env

Options:
  -h, --help    Show this help.
  --extract DIR Extract the embedded tarball to DIR without running pm2 (debug).
USAGE
}

if [ $# -lt 1 ]; then
  usage >&2
  exit 2
fi

case "$1" in
  -h|--help)
    usage
    exit 0
    ;;
  --extract)
    if [ $# -ne 2 ]; then
      echo "error: --extract requires a directory argument" >&2
      exit 2
    fi
    EXTRACT_ONLY=1
    TARGET="$2"
    ENV_FILE=""
    ;;
  *)
    if [ $# -ne 2 ]; then
      usage >&2
      exit 2
    fi
    EXTRACT_ONLY=0
    TARGET="$1"
    ENV_FILE="$2"
    ;;
esac

# ---- Validate inputs ---------------------------------------------------------

if [ "$EXTRACT_ONLY" -eq 0 ]; then
  if [ ! -f "$ENV_FILE" ]; then
    echo "error: env file not found: $ENV_FILE" >&2
    exit 1
  fi
  if ! command -v pm2 >/dev/null 2>&1; then
    echo "error: pm2 is not installed or not in PATH" >&2
    exit 1
  fi
fi

if ! command -v tar >/dev/null 2>&1; then
  echo "error: tar is not installed or not in PATH" >&2
  exit 1
fi

# ---- Locate embedded payload -------------------------------------------------

# The payload starts on the line after the __PAYLOAD__ marker.
PAYLOAD_LINE=$(awk '/^__PAYLOAD__$/ {print NR + 1; exit 0}' "$0")
if [ -z "$PAYLOAD_LINE" ]; then
  echo "error: embedded payload marker not found in $0" >&2
  exit 1
fi

# ---- Resolve absolute paths BEFORE we change directory -----------------------

# Self path (this script) — read payload from here later.
SELF=$(cd "$(dirname "$0")" && pwd)/$(basename "$0")

if [ "$EXTRACT_ONLY" -eq 0 ]; then
  # Resolve env-file to an absolute path before we cd around.
  ENV_FILE_ABS=$(cd "$(dirname "$ENV_FILE")" && pwd)/$(basename "$ENV_FILE")
fi

# ---- Wipe & recreate target --------------------------------------------------

echo "→ Preparing $TARGET"
rm -rf -- "$TARGET"
mkdir -p -- "$TARGET"

# ---- Extract embedded tarball ------------------------------------------------

echo "→ Extracting build into $TARGET"
tail -n "+$PAYLOAD_LINE" "$SELF" | tar -xzf - -C "$TARGET"

if [ "$EXTRACT_ONLY" -eq 1 ]; then
  echo "✓ Extracted to $TARGET (skipped pm2)"
  exit 0
fi

# ---- Copy .env ---------------------------------------------------------------

echo "→ Installing .env"
cp -- "$ENV_FILE_ABS" "$TARGET/.env"

# ---- pm2 restart -------------------------------------------------------------

echo "→ Restarting pm2 service 'ucpb'"
pm2 del ucpb >/dev/null 2>&1 || true
cd -- "$TARGET"
pm2 start --name ucpb 'node server.js'

echo "✓ Deployed to $TARGET"
exit 0

# Everything below this marker is a binary tar.gz payload.
__PAYLOAD__
